version: "3"

services:
  angula:
    build:
      context: ./Web/app/
    tty: true

    volumes:
      - ./Web/app/:/app
    ports:
      - 5000:4200
  api:
    build:
      context: ./Api/Api
    volumes:
      - ./Api/Api:/dotnet_volume
    tty: true
    ports:
      - "5001:5001"
